export type Section = {
  title: string;
  questions: string[];
};

export const SECTIONS: Section[] = [
  {
    title: "Section 1: Personality and Cooperation",
    questions: [
      "I am a quiet and cooperative person.",
      "I have always done things my way and taken the consequences.",
      "I like to be the one to take charge.",
      "I have always had a regular way of doing things so I can avoid mistakes.",
      "I respond the same day to letters.",
      "Every now and then I ruin the good things that happen to me.",
      "I don't get excited about much anymore.",
      "I would much rather be a follower than be a leader.",
      "I go out of my way to make myself popular with others.",
      "I have always had a talent for being successful.",
    ],
  },
  {
    title: "Section 2: Fairness and Social Interactions",
    questions: [
      "I often find that I've been treated unfairly.",
      "I feel uncomfortable when people are good to me.",
      "I often feel self-conscious and tense at social gatherings.",
      "Police take too much advantage of the power they have.",
      "Sometimes, I have had to be pretty 'rough with people.",
      "Children should always obey the rules of their elders.",
      "I often feel disgusted with the way things are going.",
      "I often expect the worst to happen to me.",
      "I wouldn't mind not having many friends.",
      "I am a shy and socially inhibited person.",
    ],
  },
  {
    title: "Section 3: Rules and Behavior",
    questions: [
      "Even when I disagree, I usually let others have their way.",
      "No one should be expected to always tell the truth.",
      "I make nasty remarks to people if they deserve them.",
      "I like to follow instructions and do what others expect of me.",
      "So little of what I do is appreciated by others.",
      "Almost anything I try is easy for me.",
      "I've become more drawn into myself in recent years.",
      "I am a dramatic and showy sort of person.",
      "I always try to do what is proper.",
      "I don't depend much on other people for friendship.",
    ],
  },
  {
    title: "Section 4: Obedience and Authority",
    questions: [
      "I've never overstayed my time at a parking meter.",
      "Punishment hasn't stopped me from doing whatever I wanted.",
      "I like to arrange things to the last detail.",
      "I am often annoyed by others.",
      "I never broke any rule my parents expected me to follow.",
      "I get what I want even if I have to bully others.",
      "Nothing is more important than protecting one's moral reputation.",
      "Opportunities don't work out for me the way they do for others.",
      "I don't show much feeling anymore.",
      "What I have to say is not likely to interest others.",
    ],
  },
  {
    title: "Section 5: Excitement and Adventure",
    questions: [
      "I go out of my way to meet exciting people and to have adventures.",
      "I don't take many of my responsibilities too seriously.",
      "I'm a tough, unsentimental sort of person.",
      "Few things in life seem to stir me very much.",
      "I become very tense when I have to talk to people I don’t know.",
      "I'm a cooperative person who gives in to others.",
      "I like to act on the spur of the moment.",
      "I think ahead and then actively follow through.",
      "I have often been restless and wanted to move on to almost anywhere else.",
      "It is best to tightly control one's emotions.",
    ],
  },
  {
    title: "Section 6: Self-Criticism and Emotions",
    questions: [
      "I wish people would not blame me when things go wrong.",
      "I'm probably my own worst enemy.",
      "I have very few close ties with others.",
      "I feel anxious with people I don’t know very well.",
      "It's all right to get around the law, if you don't break it.",
      "I do a lot for others, but little is done for me.",
      "I've always believed that others don't think well of me.",
      "I am very confident.",
      "I very systematically arrange my papers and records.",
      "From past experience I know that good things don’t last.",
    ],
  },
  {
    title: "Section 7: Social Withdrawal",
    questions: [
      "Some people say I enjoy being a martyr.",
      "I am most comfortable when I'm alone.",
      "I become much more tense than others do in new situations.",
      "I always try to avoid disagreements, no matter how strongly.",
      "I look for opportunities that are exciting and new to me.",
      "There were times when my parents had trouble keeping me in line.",
      "I always finish my work before others do.",
      "Others get breaks I don’t get.",
      "I sometimes feel I deserve to be unhappy.",
      "I wait for events to take their course before deciding what to do.",
    ],
  },
  {
    title: "Section 8: Helping and Caring",
    questions: [
      "I try to take care of others before I take care of myself.",
      "I often feel that my life goes from bad to worse.",
      "I am inspired simply by being around people.",
      "I always check the speed limit and never drive faster than what's posted.",
      "I use my head, not my heart, to make decisions.",
      "I usually follow my hunches, not the information I may have.",
      "I'm never envious of the achievements of others.",
      "I preferred school subjects that were factual rather than theoretical.",
      "I plan ahead and then act decisively to make my plans happen.",
      "My heart seems to rule my head.",
    ],
  },
  {
    title: "Section 9: Optimism and Problem-Solving",
    questions: [
      "I can always see the bright side of life.",
      "I often wait for someone else to solve my problems.",
      "I do what I want without worrying about the effect on others.",
      "I react quickly to anything that might become a problem to me.",
      "I feel good about myself only when I'm helpful to others.",
      "When something little goes wrong, my whole day can be spoiled.",
      "I enjoy daydreams more than everyday realities.",
      "I'm content to sit back and let life take its course.",
      "I try to be logical rather than emotional.",
      "I prefer things that I can see and touch than things I just imagine.",
    ],
  },
  {
    title: "Section 10: Anxiety and Kindness",
    questions: [
      "Talking with someone whom I've just met is difficult.",
      "Being kindhearted is much more important than being cool and logical.",
      "Guesses about the future are more interesting to me than facts about the past.",
      "It's very easy for me to enjoy myself.",
      "I don't seem able to influence the world around me.",
      "I live in terms of my own needs, not the needs of others.",
      "I never wait for things to happen; I make them happen my way.",
      "I never voice a curse word even when I'm furious with someone.",
      "My life is guided by a need to help others.",
      "I often feel on edge, waiting for something to go wrong.",
    ],
  },
  {
    title: "Section 11: Logic and Emotions",
    questions: [
      "Even when I was a youngster I would never cheat on a test.",
      "I am always cool and objective when dealing with others.",
      "I'd rather learn how to run a machine than speculate on why it works.",
      "I'm not an easy person to get to know.",
      "I spend a lot of time thinking about the mysteries of life.",
      "I cope very easily with emotional ups and downs.",
      "I am somewhat passive and slow about organizing my life.",
      "I do what I want without worrying about pleasing others.",
      "No matter what the temptation may be, I would never do something wrong.",
      "Friends and family turn to me first for warmth and support.",
    ],
  },
  {
    title: "Section 12: Planning and Realism",
    questions: [
      "Even when life is going well, I usually expect it will soon get worse.",
      "I carefully plan and organize my work before I begin.",
      "I am impersonal and objective when I try to solve a problem.",
      "I am a realistic person who does not like to speculate about things.",
      "Some of my best friends don't know how I really feel.",
      "Others consider me cool-headed rather than warm-hearted.",
      "My sense of reality is better than my sense of imagination.",
      "I look out for myself first and then think of others.",
      "I spend a lot of effort to see that life works out well for me.",
      "I always keep my composure, no matter what's happening.",
    ],
  },
  {
    title: "Section 13: Warmth and Relationships",
    questions: [
      "I show a great deal of warmth toward my friends.",
      "Very few things have worked out well for me.",
      "I like to meet new people and learn about their lives.",
      "I can ignore personal and emotional matters in my work.",
      "I prefer to deal with realities, not with possibilities.",
      "I seem to need a lot of time to be alone with my thoughts.",
      "Feelings of the heart are of greater value than the logic of the mind.",
      "I like dreamers more than I do realists.",
      "I'm able to laugh at problems more easily than most people are.",
      "There's not much I can do, so I just wait to see what happens.",
    ],
  },
  {
    title: "Section 14: Expressiveness and Creativity",
    questions: [
      "I never get into arguments, no matter how angry I am.",
      "I express my thoughts openly and freely.",
      "I look at the job to be done, and not at the feelings of the people involved.",
      "Working on creative ideas would be ideal for me.",
      "I'm the kind of person who takes life easy and prefers to watch the passing scene.",
      "I dislike depending on anyone in my work.",
      "I see to it that things come out the way I want them to.",
      "I enjoy everyday realities more than daydreams.",
      "Lots of small things upset me.",
      "I learn best by watching and talking to people.",
    ],
  },
  {
    title: "Section 15: Sociability and Decision-Making",
    questions: [
      "I'm not content to sit back and let life take its course.",
      "Meeting new people is not something I look forward to.",
      "I seldom know how to keep a social conversation going.",
      "I always take others' feelings into account.",
      "I trust my hunches more than my observations.",
      "I tend not to act until I know what others are going to do.",
      "I prefer to make decisions on my own, with little or no advice from others.",
      "I often feel miserable for no good reason.",
      "I like being popular and doing lots of social activities.",
      "I rarely express my inner thoughts to others.",
    ],
  },
  {
    title: "Section 16: Ambition and Efficiency",
    questions: [
      "I am enthusiastic about almost all of the activities.",
      "I make a practice to depend on myself and not on others.",
      "Most of the time I'm actively involved in arranging the events in my life.",
      "There's nothing like the warm feeling of being with a group of relatives.",
      "Sometimes I am tense or depressed, and I don’t know why.",
      "I really enjoy discussions about myths and mystical events.",
      "I decide my priorities and then take firm action to achieve them.",
      "I don't hesitate to direct people to do what I think is best for them.",
      "I'm proud that I am efficient and organized.",
      "I really dislike people who become leaders for no good reason.",
    ],
  },
  {
    title: "Section 17: Influence and Leadership",
    questions: [
      "I am ambitious.",
      "I know how to charm people.",
      "Others can always rely on me to do my work diligently.",
      "Others consider me warm-hearted rather than cool-headed.",
      "I'd be willing to work for years to become someone of importance.",
      "I would enjoy selling new ideas or products to people.",
      "I usually persuade others to do exactly what I want them to do.",
      "I enjoy work that requires careful attention to details.",
      "I'm very introspective, always trying to understand my thoughts and emotions.",
      "I have great confidence in my social abilities.",
    ],
  },
  {
    title: "Section 18: Persuasion and Motivation",
    questions: [
      "I quickly size up situations and then act to make them turn out the way I want.",
      "I can persuade almost anyone to switch to my side of an argument.",
      "I will get any job done no matter what the obstacles may be.",
      "Like a good salesperson, I can successfully influence people in a socially pleasing manner.",
      "Meeting new people is something I look forward to.",
      "The welfare of those affected should be the primary consideration when a decision about them is made.",
      "I have the patience to attend to work that must be highly accurate.",
      "My sense of imagination is better than my sense of reality.",
      "I'm motivated to become one of the best in my field.",
      "I have a pleasing social style that makes people easily like me.",
    ],
  },
];


